#!/usr/bin/env python3
"""
Fleet Builder用の艦娘データ assets/data/kancolle-ships.json を生成する。

出典を2層に分けている:
  1. api_start2.json  = 艦これが配信しているマスターデータ。耐久・火力・雷装・対空・
     装甲・運・スロット数・速力・艦種はこちらを正とする。
  2. wiki/ship.json   = KanColle Wiki由来。対潜と索敵はレベル成長で決まりマスター
     データに含まれないため、この2項目だけこちらから取る。
  どちらも kcwiki/kancolle-data 経由。英語艦名は同リポジトリの tl/ship.json。

wiki側の値はマスターデータと重複する6896項目のうち19項目しか食い違わない
（99.7%一致）ことを確認済みだが、重複項目は常にマスターデータを採用する。

運はレベルで上がらず近代化改修でのみ上昇するので、掲載しているのは初期値。
耐久も同様に初期値。火力・雷装・対空・装甲はLv99到達時の最大値。

使い方: python3 scripts/build_kancolle_ships.py
"""
import json
import os
import urllib.request
from datetime import date

BASE = "https://raw.githubusercontent.com/kcwiki/kancolle-data/master"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets/data/kancolle-ships.json")
CACHE_DIR = "/tmp/kcdata"

SOURCES = {
    "master": f"{BASE}/api/api_start2.json",
    "wiki": f"{BASE}/wiki/ship.json",
    "tl": f"{BASE}/tl/ship.json",
}

# api_stype -> 英語圏コミュニティ標準の艦種略号（全言語共通で使うため翻訳不要）
STYPE = {
    1: "DE", 2: "DD", 3: "CL", 4: "CLT", 5: "CA", 6: "CAV", 7: "CVL",
    8: "BB", 9: "BB", 10: "BBV", 11: "CV", 13: "SS", 14: "SSV",
    16: "AV", 17: "LHA", 18: "CVB", 19: "AR", 20: "AS", 21: "CT", 22: "AO",
}

FIELDS = ["jp", "en", "type", "hp", "fire", "torp", "aa", "armor",
          "asw", "los", "luck", "slots", "speed", "remodel_lv", "remodel_to"]


def fetch(name, url):
    os.makedirs(CACHE_DIR, exist_ok=True)
    path = os.path.join(CACHE_DIR, name + ".json")
    if not os.path.exists(path):
        print(f"downloading {name} ...")
        urllib.request.urlretrieve(url, path)
    return json.load(open(path))


def remodel_name(ship, by_id):
    """改造先の日本語名（マスターデータの api_name）。改造がない場合は空文字。
    表示側で jp 列を引いて「英語名 (日本語名)」にするため、言語に依存しない日本語名で持つ。"""
    if not ship.get("api_afterlv"):
        return ""
    target = by_id.get(int(ship.get("api_aftershipid") or 0))
    return target["api_name"] if target else ""


def main():
    master = fetch("master", SOURCES["master"])
    wiki = fetch("wiki", SOURCES["wiki"])
    tl = fetch("tl", SOURCES["tl"])

    mst = {s["api_name"]: s for s in master["api_mst_ship"]}
    by_id = {s["api_id"]: s for s in master["api_mst_ship"]}

    ships = []
    skipped = []
    for en_name, w in wiki.items():
        jp = w.get("_japanese_name")
        s = mst.get(jp)
        if not s:
            skipped.append(en_name)
            continue
        stype = STYPE.get(s["api_stype"])
        if stype is None:
            skipped.append(en_name)
            continue
        ships.append([
            jp,
            tl.get(jp, en_name),
            stype,
            s["api_taik"][0],      # 耐久（初期値。改修で上昇するため）
            s["api_houg"][1],      # 火力（Lv99最大）
            s["api_raig"][1],      # 雷装
            s["api_tyku"][1],      # 対空
            s["api_souk"][1],      # 装甲
            w.get("_asw_max") or 0,   # 対潜（マスターデータに無いためwiki由来）
            w.get("_los_max") or 0,   # 索敵（同上）
            s["api_luck"][0],      # 運（初期値。レベルでは上がらない）
            s["api_slot_num"],
            1 if s["api_soku"] >= 10 else 0,   # 1=高速 0=低速
            s.get("api_afterlv", 0) or 0,      # 次の改造レベル（0=これ以上なし）
            remodel_name(s, by_id),
        ])

    ships.sort(key=lambda r: (r[2], r[1]))

    payload = {
        "_comment": "Generated by scripts/build_kancolle_ships.py - do not edit by hand.",
        "_sources": SOURCES,
        "_note": ("hp and luck are base values (both rise only through modernization, "
                  "not levelling). fire/torp/aa/armor are Lv99 maxima from the game's "
                  "own master data. asw/los are Lv99 maxima from KanColle Wiki, since "
                  "the master data does not carry them. remodel_lv/remodel_to come "
                  "from the master data (api_afterlv/api_aftershipid); 0/empty means "
                  "no further remodel."),
        "generated": date.today().isoformat(),
        "fields": FIELDS,
        "ships": ships,
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(payload, f, ensure_ascii=False, separators=(",", ":"))
        f.write("\n")

    size = os.path.getsize(OUT)
    print(f"wrote {OUT}: {len(ships)} ships, {size/1024:.0f} KB")
    if skipped:
        print(f"skipped {len(skipped)}: {', '.join(skipped[:5])}"
              + (" ..." if len(skipped) > 5 else ""))


if __name__ == "__main__":
    main()
