#!/usr/bin/env python3
"""
Webフォントを自前ホスト用に取得し、assets/fonts/ を生成する。

Google Fontsの読み込みは訪問者のIPアドレスをGoogleに送るため、EUではGDPR上の
問題になりうる（LG München I, 3 O 17493/20）。フォント自体はSIL OFL 1.1で再配布が
許可されているので、ファイルごと自サイトから配信する。

Googleが返すCSSは文字範囲(unicode-range)ごとに分割されたwoff2を参照しており、
ブラウザは表示する文字を含む分割ファイルだけを取得する。日本語フォントは全体で
6MB超あるが、この分割をそのまま再現することで1ページあたりの転送量を抑える。

OFLの条件として、各フォントのディレクトリにライセンス文 OFL.txt を同梱する。

ウェイトを増減する場合は FAMILIES を編集して再実行する。
使い方: python3 scripts/build_fonts.py
"""
import os
import re
import shutil
import urllib.request
from concurrent.futures import ThreadPoolExecutor

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets/fonts")

# (Google Fontsのファミリー指定, 出力ディレクトリ名, google/fonts リポジトリ内のパス)
FAMILIES = [
    ("Zen+Kaku+Gothic+New:wght@400;500;700;900", "zen-kaku-gothic-new", "ofl/zenkakugothicnew"),
    ("Space+Grotesk:wght@500;600;700", "space-grotesk", "ofl/spacegrotesk"),
    ("JetBrains+Mono:wght@500;700", "jetbrains-mono", "ofl/jetbrainsmono"),
]

# woff2 と unicode-range 分割版のCSSを返させるため、現行ブラウザのUAを名乗る
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def main():
    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(OUT)

    css_parts = []
    downloads = []
    for spec, dirname, repo_path in FAMILIES:
        famdir = os.path.join(OUT, dirname)
        os.makedirs(famdir)
        css = get(f"https://fonts.googleapis.com/css2?family={spec}&display=swap").decode()

        def local(m):
            url = m.group(1)
            name = url.rsplit("/", 1)[1]
            downloads.append((url, os.path.join(famdir, name)))
            return f"url(/assets/fonts/{dirname}/{name})"

        css = re.sub(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", local, css)
        css_parts.append(css)

        with open(os.path.join(famdir, "OFL.txt"), "wb") as f:
            f.write(get(f"https://raw.githubusercontent.com/google/fonts/main/{repo_path}/OFL.txt"))

    unique = dict(downloads)

    def fetch(item):
        url, path = item
        with open(path, "wb") as f:
            f.write(get(url))

    with ThreadPoolExecutor(max_workers=16) as pool:
        list(pool.map(fetch, unique.items()))

    header = ("/* Generated by scripts/build_fonts.py - do not edit by hand.\n"
              "   Fonts are licensed under the SIL Open Font License 1.1;\n"
              "   see OFL.txt in each font directory. */\n")
    with open(os.path.join(OUT, "fonts.css"), "w") as f:
        f.write(header + "\n".join(css_parts))

    total = sum(os.path.getsize(p) for p in unique.values())
    print(f"{len(unique)} font files, {total / 1024 / 1024:.1f} MB -> {OUT}")


if __name__ == "__main__":
    main()
