#!/usr/bin/env python3
"""
経験値計算機用の艦娘経験値テーブル assets/data/kancolle-exp.json を生成する。

出典: KC3改（KC3Kai, MIT License, Copyright (c) KC3Kai contributors）の
      src/data/exp_ship.json。形式は level -> [次レベルまでの経験値, そのレベルの累計]。

生成時に日本の攻略Wiki（wikiwiki.jp/kancolle/経験値）と1レベルずつ照合し、
食い違いがあれば書き出さずに止める。
  - Wikiのケッコン後(Lv100以降)の表は「Lv100を0とした累計」なので累計は比べられない。
    比べるのは「前のレベルからの必要経験値」の方（両者で基準が同じ）。
  - Lv99→100 はケッコンカッコカリで上がるため必要経験値0。

現在の上限は Lv188（2026/05/29 のアップデートで185→188）。

使い方: python3 scripts/build_kancolle_exp.py
"""
import html
import json
import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets/data/kancolle-exp.json")
KC3_URL = "https://raw.githubusercontent.com/KC3Kai/KC3Kai/master/src/data/exp_ship.json"
WIKI_URL = "https://wikiwiki.jp/kancolle/%E7%B5%8C%E9%A8%93%E5%80%A4"
UA = {"User-Agent": "Mozilla/5.0 (Macintosh) Chrome/131.0"}
MARRIAGE_LEVEL = 100


def get(url):
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60) as r:
        return r.read().decode("utf-8", "ignore")


def wiki_steps():
    text = re.sub(r"<[^>]+>", " ", get(WIKI_URL))
    text = re.sub(r"\s+", " ", html.unescape(text))
    end = text.find("現在の上限値")
    if end < 0:
        sys.exit("wiki layout changed: level table end marker not found")
    steps = {}
    for m in re.finditer(r"(?<![\d,])(\d{1,3}) ([\d,]{3,11}) ([\d,]{3,11})(?![\d,])", text[:end]):
        lv = int(m.group(1))
        if 2 <= lv <= 250:
            steps[lv] = int(m.group(2).replace(",", ""))
    return steps


def main():
    kc3 = json.loads(get(KC3_URL))
    max_level = max(int(k) for k in kc3)
    total = [0] * (max_level + 1)  # total[lv] = 累計経験値（Lv1 = 0）
    for lv in range(1, max_level + 1):
        total[lv] = kc3[str(lv)][1]

    steps = wiki_steps()
    compared = mismatches = 0
    for lv in range(2, max_level + 1):
        if lv == MARRIAGE_LEVEL:
            continue
        if lv not in steps:
            sys.exit(f"wiki table has no row for Lv{lv}; cannot verify")
        compared += 1
        if total[lv] - total[lv - 1] != steps[lv]:
            mismatches += 1
            print(f"MISMATCH Lv{lv}: KC3 {total[lv] - total[lv - 1]:,} / wiki {steps[lv]:,}")
    if mismatches:
        sys.exit(f"{mismatches} mismatches; not writing {OUT}")
    if max(steps) != max_level:
        sys.exit(f"level cap differs: KC3 Lv{max_level} / wiki Lv{max(steps)}")

    payload = {
        "_comment": "Generated by scripts/build_kancolle_exp.py - do not edit by hand.",
        "_source": "KC3Kai src/data/exp_ship.json (MIT License, Copyright (c) KC3Kai contributors)",
        "_verified": f"every per-level step (Lv2-{max_level}) matches wikiwiki.jp/kancolle/経験値",
        "max_level": max_level,
        "marriage_level": MARRIAGE_LEVEL,
        "total": total,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(payload, f, separators=(",", ":"))
        f.write("\n")
    print(f"wrote {OUT}: Lv1-{max_level}, {compared} steps verified against the wiki")


if __name__ == "__main__":
    main()
